// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

import { Webpb } from 'webpb';

export namespace ErrorProto {
    export enum ErrorCode {
        OK = 0,
        ERROR = 1,
    }

    export interface IErrorMessage {
        code: ErrorProto.ErrorCode;
        message?: string;
    }

    export class ErrorMessage implements IErrorMessage {
        code!: ErrorProto.ErrorCode;
        message?: string;
        META: () => Webpb.WebpbMeta;

        private constructor(p: IErrorMessage) {
            Webpb.assign(p, this, []);
            this.META = () => ({
                class: 'ErrorMessage',
                method: '',
                path: ''
            });
        }

        static create(properties: IErrorMessage): ErrorMessage {
            return new ErrorMessage(properties);
        }
    }
}
