// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb
package com.github.jg513.example.store;

import com.github.jg513.webpb.WebpbMessage;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class EmptyPb implements WebpbMessage {

    @Getter
    @Setter
    @Accessors(chain = true)
    public static class EnclosingPb implements WebpbMessage {
    }
}
