// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

package com.github.jg513.example.store;

import com.squareup.wire.Message;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class Project implements Message {
}
