// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb
package com.github.jg513.example.store;

import com.github.jg513.webpb.WebpbMessage;
import lombok.Setter;
import lombok.Getter;
import lombok.experimental.Accessors;

@Setter
@Getter
@Accessors(chain = true)
public class StoreResponse implements WebpbMessage {

    private StorePb store;

    private StoreNestedPb nested;

    @Setter
    @Getter
    @Accessors(chain = true)
    public static class StoreNestedPb implements WebpbMessage {

        private String employee;
    }
}
