// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb
package com.github.jg513.example.store;

import com.github.jg513.webpb.WebpbMessage;
import com.somewhere.Const;
import javax.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class StoreRequest implements WebpbMessage {

    public static final String METHOD = "GET";

    public static final String PATH = "/stores/{id}";

    @Pattern(regexp = Const.EMAIL_REGEX)
    private String email;
}
