// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

package com.github.jg513.example.store;

import com.somewhere.Const;
import com.squareup.wire.Message;
import java.util.List;
import java.util.Map;
import javax.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class StoreRequest implements Message {

    public static final String METHOD = "GET";

    public static final String PATH = "/stores/{id}";

    @Pattern(regexp = Const.EMAIL_REGEX)
    private String email;

    private Boolean valid;

    private Map<String, Integer> data;

    private Map<String, Project> projects;

    private List<Integer> unpacked;

    private List<Integer> packed;

    private List<Project> projectList;

    private Project project;

    private Long max;

    private Map<Long, Integer> longMap;

    private Map<Long, Project> projectMap;

    private Map<Long, StoreType> typeMap;

    private byte[] binary;

    private StoreType type;

    private Float floatData;

    private Long stringField;

    private String anyName;

    private Project anyProject;

    private StoreType anyStore;
}
