// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

package com.github.jg513.example.store;

public enum StoreType {

    NORMAL(0);

    private int code;

    StoreType(int code) {
        this.code = code;
    }

    public static StoreType of(int code) {
        switch (code) {
            case 0:
                return NORMAL;
            default:
                return null;
        }
    }

    public int getCode() {
        return this.code;
    }
}
