// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

package com.github.jg513.example.resource;

import com.squareup.wire.Message;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class PagingPb implements Message {

    private Integer page;

    private Integer size;

    private Integer totalCount;

    private Integer totalPage;
}
