// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb
package com.github.jg513.example.error;

public enum ErrorCode {

    OK(0), ERROR(1);

    int code;

    private ErrorCode(int code) {
        this.code = code;
    }

    public static ErrorCode of(int code) {
        switch(code) {
            case 0:
                return OK;
            case 1:
                return ERROR;
            default:
                return null;
        };
    }

    public int getCode() {
        return this.code;
    }
}
