// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Error.proto
package com.github.jg513.example.error;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum ErrorCode implements WireEnum {
    OK(0),
    ERROR(1);

    public static final ProtoAdapter<ErrorCode> ADAPTER = new ProtoAdapter_ErrorCode();

    private final int value;

    ErrorCode(int value) {
        this.value = value;
    }

    /** Return the constant for {@code value} or null. */
    public static ErrorCode fromValue(int value) {
        switch (value) {
            case 0:
                return OK;
            case 1:
                return ERROR;
            default:
                return null;
        }
    }

    @Override
    public int getValue() {
        return value;
    }

    private static final class ProtoAdapter_ErrorCode extends EnumAdapter<ErrorCode> {

        ProtoAdapter_ErrorCode() {
            super(ErrorCode.class);
        }

        @Override
        protected ErrorCode fromValue(int value) {
            return ErrorCode.fromValue(value);
        }
    }
}
