package com.github.jg513.webpb.core;

public class Const {

    public static final String HEADER = "Code generated by Webpb compiler, do not edit.";

    public static final String GIT_URL = "https://github.com/jg513/webpb";
}
