package io.webpb.cli.writers.java;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;
import com.squareup.wire.schema.Type;
import io.webpb.cli.common.specs.PendingTypeSpec;
import io.webpb.cli.common.CodeWriter;
import io.webpb.cli.common.CodeWriterContext;
import io.webpb.cli.common.PendingSpec;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class JavaWriter extends CodeWriter {
    public JavaWriter(CodeWriterContext options) {
        super(options);
    }

    @Override
    public Void call() throws Exception {
        JavaGenerator generator = JavaGenerator.create(context.getSchema());
        while (true) {
            PendingSpec spec = context.getSpecs().poll();
            if (spec == null) {
                return null;
            }
            if (!(spec instanceof PendingTypeSpec)) {
                continue;
            }
            Type type = ((PendingTypeSpec) spec).getType();
            TypeSpec typeSpec = generator.generateType(type);
            ClassName javaTypeName = generator.generatedTypeName(type);
            JavaFile.Builder builder = JavaFile.builder(javaTypeName.packageName(), typeSpec)
                .indent("    ")
                .addFileComment("$L", "Code generated by Webpb compiler, do not edit.");

            JavaFile javaFile = builder.build();
            Path path = Paths.get(context.getOut());
            try {
                javaFile.writeTo(path);
            } catch (IOException e) {
                throw new IOException("Error emitting " + javaFile.packageName
                    + '.' + javaFile.typeSpec.name + " to " + context.getOut(), e);
            }
        }
    }
}
