// Code generated by Webpb compiler, do not edit.
// https://github.com/jg513/webpb

package com.google.protobuf;

import com.squareup.wire.Message;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class Any implements Message {

    private String type_url;

    private byte[] value;
}
