package com.github.jg513.webpb.common;

import com.squareup.wire.schema.ProtoMember;

import static com.squareup.wire.schema.Options.ENUM_VALUE_OPTIONS;
import static com.squareup.wire.schema.Options.FIELD_OPTIONS;
import static com.squareup.wire.schema.Options.FILE_OPTIONS;
import static com.squareup.wire.schema.Options.MESSAGE_OPTIONS;

public class Const {
    public static final String HEADER = "Code generated by Webpb compiler, do not edit.";

    public static final String GIT_URL = "https://github.com/jg513/webpb";

    public static final ProtoMember ENUM_DEPRECATED = ProtoMember.get(ENUM_VALUE_OPTIONS, "deprecated");

    public static final ProtoMember METHOD = ProtoMember.get(MESSAGE_OPTIONS, "method");

    public static final ProtoMember PATH = ProtoMember.get(MESSAGE_OPTIONS, "path");

    public static final ProtoMember OMITTED = ProtoMember.get(FIELD_OPTIONS, "omitted");

    public static final ProtoMember JAVA_ANNO = ProtoMember.get(FIELD_OPTIONS, "java_anno");

    public static final ProtoMember JAVA_IMPORT = ProtoMember.get(FILE_OPTIONS, "java_import");

    public static final ProtoMember JAVA_MESSAGE_ANNO = ProtoMember.get(FILE_OPTIONS, "java_message_anno");

    public static final ProtoMember JAVA_GETTER = ProtoMember.get(FILE_OPTIONS, "java_getter");

    public static final ProtoMember JAVA_SETTER = ProtoMember.get(FILE_OPTIONS, "java_setter");
}
