// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Store.proto
package com.github.jg513.example.store;

import com.github.jg513.webpb.core.WebpbMessage;
import com.github.jg513.webpb.options.MessageOptions;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import okio.ByteString;

@Getter
@Setter
@Accessors(chain = true)
@ToString
public final class EmptyPb extends Message<EmptyPb, EmptyPb.Builder> implements WebpbMessage {

    public static final MessageOptions MESSAGE_OPTIONS = new MessageOptions.Builder().build();

    public static final ProtoAdapter<EmptyPb> ADAPTER = new ProtoAdapter_EmptyPb();

    private static final long serialVersionUID = 0L;

    public EmptyPb() {
        this(ByteString.EMPTY);
    }

    public EmptyPb(ByteString unknownFields) {
        super(ADAPTER, unknownFields);
    }

    @Override
    public MessageOptions messageOptions() {
        return MESSAGE_OPTIONS;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof EmptyPb)) return false;
        EmptyPb o = (EmptyPb) other;
        return unknownFields().equals(o.unknownFields());
    }

    @Override
    public int hashCode() {
        return unknownFields().hashCode();
    }

    public static final class Builder extends Message.Builder<EmptyPb, Builder> {

        public Builder() {}

        @Override
        public EmptyPb build() {
            return new EmptyPb(super.buildUnknownFields());
        }
    }

    @Getter
    @Setter
    @Accessors(chain = true)
    @ToString
    public static final class EnclosingPb extends Message<EnclosingPb, EnclosingPb.Builder>
            implements WebpbMessage {

        public static final MessageOptions MESSAGE_OPTIONS = new MessageOptions.Builder().build();

        public static final ProtoAdapter<EnclosingPb> ADAPTER = new ProtoAdapter_EnclosingPb();

        private static final long serialVersionUID = 0L;

        public static final Long DEFAULT_INNERSTRING = 0L;

        @WireField(
                tag = 24,
                adapter = "com.squareup.wire.ProtoAdapter#INT64",
                label = WireField.Label.REQUIRED)
        private Long innerString;

        public EnclosingPb() {
            super(ADAPTER, ByteString.EMPTY);
        }

        public EnclosingPb(Long innerString) {
            this(innerString, ByteString.EMPTY);
        }

        public EnclosingPb(Long innerString, ByteString unknownFields) {
            super(ADAPTER, unknownFields);
            this.innerString = innerString;
        }

        @Override
        public MessageOptions messageOptions() {
            return MESSAGE_OPTIONS;
        }

        @Override
        public Builder newBuilder() {
            Builder builder = new Builder();
            builder.innerString = innerString;
            builder.addUnknownFields(unknownFields());
            return builder;
        }

        @Override
        public boolean equals(Object other) {
            if (other == this) return true;
            if (!(other instanceof EnclosingPb)) return false;
            EnclosingPb o = (EnclosingPb) other;
            return unknownFields().equals(o.unknownFields()) && innerString.equals(o.innerString);
        }

        @Override
        public int hashCode() {
            int result = super.hashCode;
            if (result == 0) {
                result = unknownFields().hashCode();
                result = result * 37 + innerString.hashCode();
                super.hashCode = result;
            }
            return result;
        }

        public static final class Builder extends Message.Builder<EnclosingPb, Builder> {

            public Long innerString;

            public Builder() {}

            public Builder innerString(Long innerString) {
                this.innerString = innerString;
                return this;
            }

            @Override
            public EnclosingPb build() {
                if (innerString == null) {
                    throw Internal.missingRequiredFields(innerString, "innerString");
                }
                return new EnclosingPb(innerString, super.buildUnknownFields());
            }
        }

        private static final class ProtoAdapter_EnclosingPb extends ProtoAdapter<EnclosingPb> {

            public ProtoAdapter_EnclosingPb() {
                super(
                        FieldEncoding.LENGTH_DELIMITED,
                        EnclosingPb.class,
                        "type.googleapis.com/StoreProto.EmptyPb.EnclosingPb");
            }

            @Override
            public int encodedSize(EnclosingPb value) {
                return ProtoAdapter.INT64.encodedSizeWithTag(24, value.innerString)
                        + value.unknownFields().size();
            }

            @Override
            public void encode(ProtoWriter writer, EnclosingPb value) throws IOException {
                ProtoAdapter.INT64.encodeWithTag(writer, 24, value.innerString);
                writer.writeBytes(value.unknownFields());
            }

            @Override
            public EnclosingPb decode(ProtoReader reader) throws IOException {
                Builder builder = new Builder();
                long token = reader.beginMessage();
                for (int tag; (tag = reader.nextTag()) != -1; ) {
                    switch (tag) {
                        case 24:
                            builder.innerString(ProtoAdapter.INT64.decode(reader));
                            break;
                        default:
                            {
                                reader.readUnknownField(tag);
                            }
                    }
                }
                builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
                return builder.build();
            }

            @Override
            public EnclosingPb redact(EnclosingPb value) {
                Builder builder = value.newBuilder();
                builder.clearUnknownFields();
                return builder.build();
            }
        }
    }

    private static final class ProtoAdapter_EmptyPb extends ProtoAdapter<EmptyPb> {

        public ProtoAdapter_EmptyPb() {
            super(
                    FieldEncoding.LENGTH_DELIMITED,
                    EmptyPb.class,
                    "type.googleapis.com/StoreProto.EmptyPb");
        }

        @Override
        public int encodedSize(EmptyPb value) {
            return value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, EmptyPb value) throws IOException {
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public EmptyPb decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    default:
                        {
                            reader.readUnknownField(tag);
                        }
                }
            }
            builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
            return builder.build();
        }

        @Override
        public EmptyPb redact(EmptyPb value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
