// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Store.proto
package com.github.jg513.example.store;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum StoreType implements WireEnum {
    NORMAL(0);

    public static final ProtoAdapter<StoreType> ADAPTER = new ProtoAdapter_StoreType();

    private final int value;

    StoreType(int value) {
        this.value = value;
    }

    /** Return the constant for {@code value} or null. */
    public static StoreType fromValue(int value) {
        switch (value) {
            case 0:
                return NORMAL;
            default:
                return null;
        }
    }

    @Override
    public int getValue() {
        return value;
    }

    private static final class ProtoAdapter_StoreType extends EnumAdapter<StoreType> {

        ProtoAdapter_StoreType() {
            super(StoreType.class);
        }

        @Override
        protected StoreType fromValue(int value) {
            return StoreType.fromValue(value);
        }
    }
}
