// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: Store.proto
package com.github.jg513.example.store;

import com.github.jg513.webpb.core.WebpbMessage;
import com.github.jg513.webpb.options.MessageOptions;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import okio.ByteString;

@Getter
@Setter
@Accessors(chain = true)
@ToString
public final class UserMpLoginRequest
        extends Message<UserMpLoginRequest, UserMpLoginRequest.Builder> implements WebpbMessage {

    public static final MessageOptions MESSAGE_OPTIONS = new MessageOptions.Builder().build();

    public static final ProtoAdapter<UserMpLoginRequest> ADAPTER =
            new ProtoAdapter_UserMpLoginRequest();

    private static final long serialVersionUID = 0L;

    public static final String DEFAULT_APPID = "";

    public static final String DEFAULT_CODE = "";

    @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.REQUIRED)
    private String appId;

    @WireField(
            tag = 2,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.REQUIRED)
    private String code;

    public UserMpLoginRequest() {
        super(ADAPTER, ByteString.EMPTY);
    }

    public UserMpLoginRequest(String appId, String code) {
        this(appId, code, ByteString.EMPTY);
    }

    public UserMpLoginRequest(String appId, String code, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.appId = appId;
        this.code = code;
    }

    @Override
    public MessageOptions messageOptions() {
        return MESSAGE_OPTIONS;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.appId = appId;
        builder.code = code;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof UserMpLoginRequest)) return false;
        UserMpLoginRequest o = (UserMpLoginRequest) other;
        return unknownFields().equals(o.unknownFields())
                && appId.equals(o.appId)
                && code.equals(o.code);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + appId.hashCode();
            result = result * 37 + code.hashCode();
            super.hashCode = result;
        }
        return result;
    }

    public static final class Builder extends Message.Builder<UserMpLoginRequest, Builder> {

        public String appId;

        public String code;

        public Builder() {}

        public Builder appId(String appId) {
            this.appId = appId;
            return this;
        }

        public Builder code(String code) {
            this.code = code;
            return this;
        }

        @Override
        public UserMpLoginRequest build() {
            if (appId == null || code == null) {
                throw Internal.missingRequiredFields(appId, "appId", code, "code");
            }
            return new UserMpLoginRequest(appId, code, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_UserMpLoginRequest
            extends ProtoAdapter<UserMpLoginRequest> {

        public ProtoAdapter_UserMpLoginRequest() {
            super(
                    FieldEncoding.LENGTH_DELIMITED,
                    UserMpLoginRequest.class,
                    "type.googleapis.com/StoreProto.UserMpLoginRequest");
        }

        @Override
        public int encodedSize(UserMpLoginRequest value) {
            return ProtoAdapter.STRING.encodedSizeWithTag(1, value.appId)
                    + ProtoAdapter.STRING.encodedSizeWithTag(2, value.code)
                    + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, UserMpLoginRequest value) throws IOException {
            ProtoAdapter.STRING.encodeWithTag(writer, 1, value.appId);
            ProtoAdapter.STRING.encodeWithTag(writer, 2, value.code);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public UserMpLoginRequest decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.appId(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 2:
                        builder.code(ProtoAdapter.STRING.decode(reader));
                        break;
                    default:
                        {
                            reader.readUnknownField(tag);
                        }
                }
            }
            builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
            return builder.build();
        }

        @Override
        public UserMpLoginRequest redact(UserMpLoginRequest value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
